backend:
  name: github
  repo: slashkilled/slashkill_space
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Записи"
    folder: "_posts"
    create: true
    format: "frontmatter"
    fields:
      - {label: "Заголовок / Текст", name: "body", widget: "string"}
      - {label: "Дата", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss Z"}
      - {label: "Категория", name: "category", widget: "select", options: ["shitposting", "music"]}
